# emc hyperparameter
use_next_state: True 
use_last_action: False # actor use last action. (only cds : True)

embadding_dim: 512 # : test setting

# HyperParameter - Transformer
num_heads: 2 # Critic - Transformer 모델의 헤드 수
embed_dim: 64
# HyperParameter - CDS
num_kernel: 4
mixing_embed_dim: 32
hypernet_embed: 64
adv_hypernet_embed: 64
attend_reg_coef: 0.001 # attention regulation coefficient

# Unique Hyperparameter - EMC
use_emdqn: False
emdqn_loss_weight: 0.1
emdqn_buffer_size: 1000000
emdqn_latent_dim: 4
soft_update_tau: 0.005
vdn_soft_update: True
predict_vdn_target: True
predict2_vdn_target: True
curiosity_scale: 0.1
curiosity_decay_rate: 0.9
curiosity_decay_stop: 0.0