# poca(MA-POCA) hyperparameter
use_next_state: True
use_last_action: False # actor use last action.

embadding_dim: 256 # Linear Layer Dim
td_lambda: 0.9
gamma: 0.99 # discount factor

# HyperParameter - Transformer
num_heads: 2 # Critic - Transformer 모델의 헤드 수
embed_dim: 64
mu: 0.5 # baseline loss ratio
clip_eps: 0.2 # ma-poca actor_loss에 적용되는 epsilon