# -------- RL Setting Parameters --------
LearningControl:
  env: 'i3a3b3'
  training: True
  run_step: 2000000
  test_step: 1000000 # max test step
  print_interval: 1 # episode counts
  save_interval: 5 # model checkpoint save episode interval
# ------ Game & learner Parameters ------ [Blue(team0), Red(team1)] Learning Sequence Setting
Framework: ["marl", "rsa"] # Train - ["marl", "rsa"] / Comparative Test - ["marl", "marl"]
Algorithm: ["irf","irf"] # algorithm - irf, coma, cds
train_mode: [True, False] # [team0, team1]
load_model: [False, False] # [team0, team1]
load_path: 
 - 'path-team0' #team[0]
 - 'path-team1' #team[1]
# recommend absolute path (trained model in hugging face : Trueflow/irf-paper-artifacts)

# Training HyperParameter
eps_greedy: #  start 0.3, finish 0.01, num_episode 150~200
  start: 0.3 # epsilon-greedy shcedule
  finish: 0.01
  num_episode: 200
target_update_interval: 3 # critic target network update interval
grad_norm_clip: 10 # gradient clipping
gamma: 0.99 # discount factor. emc (vdn:0.9)
optimiser: "Adam" # recommend Adam
optimiser_param: # Adam, RMSprop
  Adam:
    lr: 1.5e-4
  RMSprop:
    lr: 1.0e-4
    eps: 0.1
    alpha: 0.99